// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/fraima/fraimactl/internal/config"

import mock "github.com/stretchr/testify/mock"

// downloader is an autogenerated mock type for the downloader type
type Downloader struct {
	mock.Mock
}

// Run provides a mock function with given fields: instruction
func (_m *Downloader) Run(instruction config.DownloadInstruction) error {
	ret := _m.Called(instruction)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.DownloadInstruction) error); ok {
		r0 = rf(instruction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
