// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/fraima/fraimactl/internal/config"

import mock "github.com/stretchr/testify/mock"

// generator is an autogenerated mock type for the generator type
type Generator struct {
	mock.Mock
}

// Run provides a mock function with given fields: fileType, instruction
func (_m *Generator) Run(fileType string, instruction config.Instruction) error {
	ret := _m.Called(fileType, instruction)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, config.Instruction) error); ok {
		r0 = rf(fileType, instruction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
