- apiVersion: fraima.io/v1alpha
  kind: DownloadConfiguration
  spec:
    - name: cotainerd
      src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
      checkSum:
        src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz.sha256sum
        type: "sha256"
      path: /usr/bin/
      owner: root:root
      permission: 0645
      unzip:
        status: true
        files: 
          - bin/containerd
          - bin/containerd-shim
          - bin/containerd-shim-runc-v1
          - bin/containerd-shim-runc-v2
          - bin/containerd-stress
          - bin/ctr
