- apiVersion: fraima.io/v1alpha
  kind: Containerd
  spec:
    downloading:
      - name: cotainerd
        src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
        checkSum:
          src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz.sha256sum
          type: "sha256"
        path:  /tmp/usr/bin/
        owner: root:root
        permission: 0645
        unzip:
          status: true
          files:
            - bin/containerd
            - bin/containerd-shim
            - bin/containerd-shim-runc-v1
            - bin/containerd-shim-runc-v2
            - bin/containerd-stress
            - bin/ctr

      - name: runc
        src: https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
        path:  /tmp/usr/bin/
        owner: root:root
        permission: 0645

- apiVersion: fraima.io/v1alpha
  kind: Kubelet
  spec:
    downloading:
      - name: kubelet
        src: https://dl.k8s.io/release/v1.23.12/bin/linux/amd64/kubelet
        checkSum:
          src: "https://dl.k8s.io/v1.23.12/bin/linux/amd64/kubelet.sha256"
          type: "sha256"
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645

- apiVersion: fraima.io/v1alpha
  kind: Kubeadm
  spec:
    downloading:
      - name: kubeadm
        src: https://dl.k8s.io/release/v1.23.12/bin/linux/amd64/kubeadm
        checkSum:
          src: "https://dl.k8s.io/v1.23.12/bin/linux/amd64/kubeadm.sha256"
          type: "sha256"
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645

- apiVersion: fraima.io/v1alpha
  kind: Kubectl
  spec:
    downloading:
      - name: kubectl
        src: https://dl.k8s.io/release/v1.23.12/bin/linux/amd64/kubectl
        checkSum:
          src: "https://dl.k8s.io/v1.23.12/bin/linux/amd64/kubectl.sha256"
          type: "sha256"
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645

- apiVersion: fraima.io/v1alpha
  kind: Crictl
  spec:
    downloading:
      - name: crictl
        src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz
        path: /tmp/usr/bin/
        checkSum:
          src: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz.sha256
          type: "sha256"
        owner: root:root
        permission: 0645
        unzip:
          status: true
          files:
            - "crictl"

- apiVersion: fraima.io/v1alpha
  kind: Etcdctl
  spec:
    downloading:
      - name: etcdctl
        src: https://github.com/etcd-io/etcd/releases/download/v3.5.5/etcd-v3.5.5-linux-amd64.tar.gz
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645
        unzip:
          status: true
          files:
            - "etcd-v3.5.5-linux-amd64/etcdctl"

- apiVersion: fraima.io/v1alpha
  kind: KeyKeeper
  spec:
    downloading:
      - name: key-keeper
        src: "https://storage.yandexcloud.net/m.images/key-keeper-R3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEhOlYpv1GRY7hghCojNX5%2F20230108%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230108T191931Z&X-Amz-Expires=2592000&X-Amz-Signature=61470EBC0AA7532EA215267A1CDF9E518D37149FAC1FE8417D18840AE2B7F8D9&X-Amz-SignedHeaders=host"
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645

- apiVersion: fraima.io/v1alpha
  kind: YandexCloud
  spec:
    downloading:
      - name: key-keeper
        src: "https://storage.yandexcloud.net/m.images/key-keeper-R3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJEhOlYpv1GRY7hghCojNX5%2F20230108%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20230108T191931Z&X-Amz-Expires=2592000&X-Amz-Signature=61470EBC0AA7532EA215267A1CDF9E518D37149FAC1FE8417D18840AE2B7F8D9&X-Amz-SignedHeaders=host"
        path: /tmp/usr/bin/
        owner: root:root
        permission: 0645
