- apiVersion: fraima.io/v1alpha
  kind: Downloading
  spec:
    - name: cotainerd
      src: https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
      path: /tmp/test
      owner: root:root
      permissions: "0644"
      unzip:
        status: true
        files: 
          - bin/ctr