- apiVersion: fraima.io/v1alpha
  kind: ContainerdConfiguration
  extraArgs:
    version: 2
    plugins:
      io.containerd.grpc.v1.cri:
        containerd:
          runtimes:
            runc:
              runtime_type: "io.containerd.runc.v2"
              options:
                SystemdCgroup: true